# Generated by Django 4.1.6 on 2023-02-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_volunteerprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skillsInfo', to='profiles.skills'),
        ),
    ]
