# Generated by Django 4.1.6 on 2023-02-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_volunteerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
