# Generated by Django 4.1.6 on 2023-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='org_profile_pics/'),
        ),
    ]
